/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgosRouteImport } from './routes/riesgos'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ClientesKeyRouteImport } from './routes/clientes.$key'
import { Route as ApiSendWhatsappRouteImport } from './routes/api/send-whatsapp'
import { Route as ApiSendInstagramRouteImport } from './routes/api/send-instagram'
import { Route as ApiSendFacebookRouteImport } from './routes/api/send-facebook'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksInstagramRouteImport } from './routes/api/public/webhooks/instagram'
import { Route as ApiPublicWebhooksFacebookRouteImport } from './routes/api/public/webhooks/facebook'

const RiesgosRoute = RiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesKeyRoute = ClientesKeyRouteImport.update({
  id: '/clientes/$key',
  path: '/clientes/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendWhatsappRoute = ApiSendWhatsappRouteImport.update({
  id: '/api/send-whatsapp',
  path: '/api/send-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendInstagramRoute = ApiSendInstagramRouteImport.update({
  id: '/api/send-instagram',
  path: '/api/send-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendFacebookRoute = ApiSendFacebookRouteImport.update({
  id: '/api/send-facebook',
  path: '/api/send-facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksInstagramRoute =
  ApiPublicWebhooksInstagramRouteImport.update({
    id: '/api/public/webhooks/instagram',
    path: '/api/public/webhooks/instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksFacebookRoute =
  ApiPublicWebhooksFacebookRouteImport.update({
    id: '/api/public/webhooks/facebook',
    path: '/api/public/webhooks/facebook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/api/send-facebook': typeof ApiSendFacebookRoute
  '/api/send-instagram': typeof ApiSendInstagramRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/public/webhooks/facebook': typeof ApiPublicWebhooksFacebookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/api/send-facebook': typeof ApiSendFacebookRoute
  '/api/send-instagram': typeof ApiSendInstagramRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/api/public/webhooks/facebook': typeof ApiPublicWebhooksFacebookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/api/send-facebook': typeof ApiSendFacebookRoute
  '/api/send-instagram': typeof ApiSendInstagramRoute
  '/api/send-whatsapp': typeof ApiSendWhatsappRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/public/webhooks/facebook': typeof ApiPublicWebhooksFacebookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/catalogo'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/onboarding'
    | '/produccion'
    | '/riesgos'
    | '/api/send-facebook'
    | '/api/send-instagram'
    | '/api/send-whatsapp'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes/'
    | '/inbox/'
    | '/pedidos/'
    | '/api/public/webhooks/facebook'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/catalogo'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/onboarding'
    | '/produccion'
    | '/riesgos'
    | '/api/send-facebook'
    | '/api/send-instagram'
    | '/api/send-whatsapp'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes'
    | '/inbox'
    | '/pedidos'
    | '/api/public/webhooks/facebook'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/catalogo'
    | '/configuracion'
    | '/inventario'
    | '/login'
    | '/onboarding'
    | '/produccion'
    | '/riesgos'
    | '/api/send-facebook'
    | '/api/send-instagram'
    | '/api/send-whatsapp'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes/'
    | '/inbox/'
    | '/pedidos/'
    | '/api/public/webhooks/facebook'
    | '/api/public/webhooks/instagram'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProduccionRoute: typeof ProduccionRoute
  RiesgosRoute: typeof RiesgosRoute
  ApiSendFacebookRoute: typeof ApiSendFacebookRoute
  ApiSendInstagramRoute: typeof ApiSendInstagramRoute
  ApiSendWhatsappRoute: typeof ApiSendWhatsappRoute
  ClientesKeyRoute: typeof ClientesKeyRoute
  InboxIdRoute: typeof InboxIdRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ApiPublicWebhooksFacebookRoute: typeof ApiPublicWebhooksFacebookRoute
  ApiPublicWebhooksInstagramRoute: typeof ApiPublicWebhooksInstagramRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riesgos': {
      id: '/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof RiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$key': {
      id: '/clientes/$key'
      path: '/clientes/$key'
      fullPath: '/clientes/$key'
      preLoaderRoute: typeof ClientesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-whatsapp': {
      id: '/api/send-whatsapp'
      path: '/api/send-whatsapp'
      fullPath: '/api/send-whatsapp'
      preLoaderRoute: typeof ApiSendWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-instagram': {
      id: '/api/send-instagram'
      path: '/api/send-instagram'
      fullPath: '/api/send-instagram'
      preLoaderRoute: typeof ApiSendInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-facebook': {
      id: '/api/send-facebook'
      path: '/api/send-facebook'
      fullPath: '/api/send-facebook'
      preLoaderRoute: typeof ApiSendFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/instagram': {
      id: '/api/public/webhooks/instagram'
      path: '/api/public/webhooks/instagram'
      fullPath: '/api/public/webhooks/instagram'
      preLoaderRoute: typeof ApiPublicWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/facebook': {
      id: '/api/public/webhooks/facebook'
      path: '/api/public/webhooks/facebook'
      fullPath: '/api/public/webhooks/facebook'
      preLoaderRoute: typeof ApiPublicWebhooksFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProduccionRoute: ProduccionRoute,
  RiesgosRoute: RiesgosRoute,
  ApiSendFacebookRoute: ApiSendFacebookRoute,
  ApiSendInstagramRoute: ApiSendInstagramRoute,
  ApiSendWhatsappRoute: ApiSendWhatsappRoute,
  ClientesKeyRoute: ClientesKeyRoute,
  InboxIdRoute: InboxIdRoute,
  PedidosIdRoute: PedidosIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ApiPublicWebhooksFacebookRoute: ApiPublicWebhooksFacebookRoute,
  ApiPublicWebhooksInstagramRoute: ApiPublicWebhooksInstagramRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
