/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiesgosRouteImport } from './routes/riesgos'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ClientesKeyRouteImport } from './routes/clientes.$key'

const RiesgosRoute = RiesgosRouteImport.update({
  id: '/riesgos',
  path: '/riesgos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesKeyRoute = ClientesKeyRouteImport.update({
  id: '/clientes/$key',
  path: '/clientes/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/inbox': typeof InboxIndexRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/produccion': typeof ProduccionRoute
  '/riesgos': typeof RiesgosRoute
  '/clientes/$key': typeof ClientesKeyRoute
  '/inbox/$id': typeof InboxIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/inbox/': typeof InboxIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/produccion'
    | '/riesgos'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes/'
    | '/inbox/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/produccion'
    | '/riesgos'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes'
    | '/inbox'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/produccion'
    | '/riesgos'
    | '/clientes/$key'
    | '/inbox/$id'
    | '/pedidos/$id'
    | '/clientes/'
    | '/inbox/'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ProduccionRoute: typeof ProduccionRoute
  RiesgosRoute: typeof RiesgosRoute
  ClientesKeyRoute: typeof ClientesKeyRoute
  InboxIdRoute: typeof InboxIdRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  InboxIndexRoute: typeof InboxIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riesgos': {
      id: '/riesgos'
      path: '/riesgos'
      fullPath: '/riesgos'
      preLoaderRoute: typeof RiesgosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$key': {
      id: '/clientes/$key'
      path: '/clientes/$key'
      fullPath: '/clientes/$key'
      preLoaderRoute: typeof ClientesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ProduccionRoute: ProduccionRoute,
  RiesgosRoute: RiesgosRoute,
  ClientesKeyRoute: ClientesKeyRoute,
  InboxIdRoute: InboxIdRoute,
  PedidosIdRoute: PedidosIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  InboxIndexRoute: InboxIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
